### ISSUE TITLE
Update extend_class to accept a list of default classes

### ISSUE THREAD

**Issue by dsrees** [cblavier/phx_component_helpers#12]
In Phoenix, you can pass a list to `class` and it will resolve a single class string. It would be great to support this functionality as well in `extend_class/3`

```elixir
# Phoenix example
<span class={[
    "text-sm font-semibold",
    @important && "uppercase",
    if Enum.empty(@errors, do: "text-gray-900", else: "text-red-600"
]}>


# extend_class example
PhxComponentHelpers.extend_class(
        assigns,
        [
            "text-sm font-semibold",
            @important && "uppercase",
            if Enum.empty(@errors, do: "text-gray-900", else: "text-red-600"
        ]
      )
```

I was going to work on this, but wanted to open an issue and get some feedback before continuing. I noticed there's not much activity in the library (it's such a simple API that doesn't need much modification) so wanted to check the pulse before opening a PR. Thanks

**Comment by cblavier** [comment]
It would be a great addition, thank Daniel.

I should have another look at all `phx_component_helpers` APIs: a lot happened on the Phoenix side since the library was created.

**Comment by dsrees** [comment]
That'd be 💯. I'd love to make more use of `phx_component_helpers` in our codebase, but am hesitant to since phoenix is changing so rapidly and this API hasn't been updated recently (as a maintainer, I get it, life gets busy)

Should I work on this addition or do you want to think over the APIs first before I make a potentially conflicting change?

**Comment by cblavier** [comment]
If it can make you feel more confident, we're still using this library in all our components at phenixdigital, so we will maintain it for the foreseeable future.

But it is also true this library is a bit less useful than it used to be. Mainly since Heex introduced some syntax sugar to pass all assigns at once or to concat CSS classes.

Still, on complex components, it can make a difference.

It's up to you Daniel :)

**Comment by dsrees** [comment]
I'll get a PR open shortly then

**Comment by cblavier** [comment]
thanks for the PR, it's been merged and will shortly be shipped in a new release
