### ISSUE TITLE
order of "forward_assigns" kills other assigns

### ISSUE THREAD

**Issue by maxmannen** [cblavier/phx_component_helpers#3]
|> forward_assigns(merge: %{foo: "bar"})
  |> extend_class(@css_table)
works

  |> extend_class(@css_table)
 |> forward_assigns(merge: %{foo: "bar"})
just leaves :foo as assigns

bug or hidden feature?

**Comment by cblavier** [comment]
It seems weird, indeed
I will work on a test case to reproduce this today

**Comment by cblavier** [comment]
Just tested it, this is working as intended. Cf `forward_assigns/2` documentation : 

> Forward and filter assigns to sub components. **By default it doesn't forward anything** unless you provide it with any combination of the options described below.

So in your second code sample, you would have to write something like this to make `forward_assigns` also forward your css classes.
```
assigns
|> extend_class(@css_table)
|> forward_assigns(merge: %{foo: "bar"}, take: [:class, :heex_class])
```

**Comment by maxmannen** [comment]
My bad. Thanks!
