### ISSUE TITLE
extend_class removes all sibling selector variants, even when they don't conflict with default classes

### ISSUE THREAD

**Issue by omginbd** [cblavier/phx_component_helpers#8]
### Expected Behavior
When calling extend_class with a function that returns [sibling selector variant classes](https://tailwindcss.com/blog/tailwindcss-2-2#sibling-selector-variants) (i.e. peer-* and group-* type classes) only the classes that conflict with the default classes would be overwritten.
E.g.
```elixir
%{class: "peer-checked:bg-indigo-500"}
|> extend_class(fn _assigns -> "peer-checked:bg-red-500 peer-focus:ring-2" end)

%{class: "peer-checked:bg-indigo-500 peer-focus:ring-2"}
```

### Actual Behavior
```elixir
%{class: "peer-checked:bg-indigo-500"}
|> extend_class(fn _assigns -> "peer-checked:bg-red-500 peer-focus:ring-2" end)

# note that "peer-focus:ring-2" is removed erroneously
%{class: "peer-checked:bg-indigo-500"}
```

Thanks for the awesome library!

**Comment by omginbd** [comment]
🤦 Closing as this looks like a dupe of #4 
Sorry!

**Comment by cblavier** [comment]
You're right this is a real issue, but I couldn't find a proper algorithm yet.
I'll take some time to think about it again.

In the meantime, if you want to check the code by yourself: https://github.com/cblavier/phx_component_helpers/blob/main/lib/phx_component_helpers/css.ex
